### ISSUE TITLE
Display all the public ssh keys in the UI

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci_deploy#16]
Would be convenient to display all the public ssh keys in the UI (like the executor show pages).

Would speed up adding them to github.

**Comment by DrTom** [comment]
This solution would be brittle. We will have to think about a completely different way for the repository authentication problem. 

For now I would suggest some other approach: since you inventory is independent you can write your little playbook that does this after you run the normal cider-ci playbook.
